// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentModel() {
  return window['go']['main']['App']['CurrentModel']();
}

export function GetResponse(arg1) {
  return window['go']['main']['App']['GetResponse'](arg1);
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function PullModel(arg1) {
  return window['go']['main']['App']['PullModel'](arg1);
}

export function PullModelStream(arg1) {
  return window['go']['main']['App']['PullModelStream'](arg1);
}

export function ReturnProgress() {
  return window['go']['main']['App']['ReturnProgress']();
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}
