// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetResponse(arg1) {
  return window['go']['main']['App']['GetResponse'](arg1);
}
