// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentModel():Promise<string>;

export function GetResponse(arg1:string):Promise<string>;

export function ListModels():Promise<Array<string>>;

export function PullModel(arg1:string):Promise<Array<string>>;

export function PullModelStream(arg1:string):Promise<Array<string>>;

export function ReturnProgress():Promise<Array<number>>;

export function SetModel(arg1:string):Promise<boolean>;
